from Actividad2 import CentroEducativo
datos=CentroEducativo()
print("Ingresa estos datos")
print("Sociedad anonima")
print("Representante")
print("Correo representante")
texto1=input("Datos Sociedad anónima 1")
texto2=input("Datos Sociedad anónima 2")
texto3=input("Datos Sociedad anónima 3")
texto4=input("Datos Sociedad anónima 4")
texto5=input("Datos Sociedad anónima 5")
print("Se han asignado representantes a los centros educativos:")
print(texto1+" "+ datos.resultado1)
print(texto2+" "+ datos.resultado1)
print(texto3+" "+ datos.resultado1)
print(texto3+" "+ datos.resultado1)
print(texto4+" "+ datos.resultado1)
print(texto5+" "+ datos.resultado5)

